import Head from "next/head";
import { Button, Form } from "react-bootstrap";
import { useRef, FormEvent } from "react";

function Contact() {
    const nameRef = useRef(null);
    const emailRef = useRef(null);
    const messageRef = useRef(null);

    const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        console.log("メール送信");

        let data = {
            name: nameRef.current?.value ?? "",
            email: emailRef.current?.value ?? "",
            message: messageRef.current?.value ?? "",
        };

        console.log("data",data);
        
        await fetch("/api/sendmail", {
            method: "POST",
            headers: {
                Accept: "application/json, text/plain",
                "Content-Type": "application/json",
            },
            body: JSON.stringify(data),
        }).then((res) => {
            if (res.status === 200) console.log("メース送信成功");
        });
    };
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container mt-5">
                <h2 className="mb-3 p-3 text-center">Next.js Gmailアプリ</h2>
                <Form onSubmit={(e) => handleSubmit(e)}>
                    <div className="mb-3">
                        <label htmlFor="">お名前</label>
                        <input
                            type="text"
                            className="form-control text-gray-800"
                            id="name"
                            required
                            ref={nameRef}
                        />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="email">メールアドレス</label>
                        <input
                            type="email"
                            className="form-control text-gray-800"
                            id="name"
                            required
                            ref={emailRef}
                        />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="message">メッセージ</label>
                        <textarea
                            className="form-control text-gray-800"
                            id="name"
                            required
                            ref={messageRef}
                        />
                    </div>
                    <Button type="submit" className="btn btn-primary">
                        メール送信
                    </Button>
                </Form>
            </div>
        </div>
    );
}

export default Contact;

