
development:
  db: "postgresql://postgres:password@maji-noka-db-1/web_development"
test:
  db: "postgresql://postgres:password@maji-noka-test_db-1/postgres"
production:
  db: <%= "postgresql://#{ENV['DB_USERNAME']}:#{ENV['PRO_DATABASE_PASSWORD']}@#{ENV['DB_HOST']}:5432/maji_database" %>
